# Core configuration is borrowed from http://sass-guidelin.es/#scss-lint
# SCSS-Lint options https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
# Is there a way to ignore `#fff` and `#000` colors for enabled `ColorVariable`?
# Yes, there is https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#disablelinterreason `// scss-lint:disable ColorVariable`
# Looks like `scss-lint` disabler works per file, not per rule, which sucks :(
# Consider adding `PropertyCount`
# Add custom `PropertySortOrder`, `[PropertyUnits](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#propertyunits)`
# Update `SelectorFormat` regex to include `@breakpoint` naming convention
# Change `SpaceAfterPropertyColon` on `aligned`?
# Update `VariableForProperty`, add new properties

linters:

  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true

  BorderZero:
    enabled: true

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: true
    style: silent

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    character: tab
    width: 1

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: true

  NameFormat:
    enabled: false
    convention: ^\.(_)?[a-z]+-[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$
    allow_leading_underscore: false

  NestingDepth:
    enabled: true
    max_depth: 3

  PlaceholderInExtend:
    enabled: true

  PropertySpelling:
    enabled: true
    extra_properties: []

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    # class_convention: '^(?:u|is|has)\-[a-z][a-zA-Z0-9]*$|^(?!u|is|has)[a-zA-Z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$'

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: false

  SpaceAfterVariableName:
    enabled: false

  SpaceAroundOperator:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  # VariableForProperty:
  #     enabled: true
  #     properties:
  #       - color
  #       - font

  VendorPrefixes:
    enabled: true
    identifier_list: base
    include: []
    exclude: []

  ZeroUnit:
    enabled: true

  PropertySortOrder:
    enabled: true
    separate_groups: false
    ignore_unspecified: false
    order:
      - display
      - content
      - box-sizing
      - flex-direction
      - flex-order
      - flex-pack
      - flex-align
      - visibility
      - opacity
      - position
      - top
      - right
      - bottom
      - left
      - width
      - height
      - min-width
      - min-height
      - max-width
      - max-height
      - z-index
      - float
      - clear
      - overflow
      - overflow-x
      - overflow-y
      - clip
      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left
      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left
      - background
      - background-color
      - background-image
      - background-attachment
      - background-position
      - background-position-x
      - background-position-y
      - background-clip
      - background-origin
      - background-size
      - background-repeat
      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset
      - border
      - border-spacing
      - border-collapse
      - border-width
      - border-style
      - border-color
      - border-top
      - border-top-width
      - border-top-style
      - border-top-color
      - border-right
      - border-right-width
      - border-right-style
      - border-right-color
      - border-bottom
      - border-bottom-width
      - border-bottom-style
      - border-bottom-color
      - border-left
      - border-left-width
      - border-left-style
      - border-left-color
      - border-radius
      - border-top-left-radius
      - border-top-right-radius
      - border-bottom-right-radius
      - border-bottom-left-radius
      - border-image
      - border-image-source
      - border-image-slice
      - border-image-width
      - border-image-outset
      - border-image-repeat
      - border-top-image
      - border-right-image
      - border-bottom-image
      - border-left-image
      - border-corner-image
      - border-top-left-image
      - border-top-right-image
      - border-bottom-right-image
      - border-bottom-left-image
      - box-decoration-break
      - box-shadow
      - table-layout
      - caption-side
      - empty-cells
      - list-style
      - list-style-position
      - list-style-type
      - list-style-image
      - quotes
      - counter-increment
      - counter-reset
      - vertical-align
      - font
      - font-family
      - font-size
      - font-size-adjust
      - font-stretch
      - font-style
      - font-variant
      - font-weight
      - color
      - line-height
      - letter-spacing
      - text-align
      - text-align-last
      - text-decoration
      - text-emphasis
      - text-emphasis-position
      - text-emphasis-style
      - text-emphasis-color
      - text-indent
      - text-justify
      - text-outline
      - text-transform
      - text-wrap
      - text-overflow
      - text-overflow-ellipsis
      - text-overflow-mode
      - text-shadow
      - white-space
      - word-spacing
      - word-wrap
      - word-break
      - tab-size
      - hyphens
      - src
      - filter
      - resize
      - cursor
      - nav-index
      - nav-up
      - nav-right
      - nav-down
      - nav-left
      - transition
      - transition-delay
      - transition-timing-function
      - transition-duration
      - transition-property
      - transform
      - transform-origin
      - animation
      - animation-name
      - animation-duration
      - animation-play-state
      - animation-timing-function
      - animation-delay
      - animation-iteration-count
      - animation-direction
      - pointer-events
      - unicode-bidi
      - direction
      - columns
      - column-span
      - column-width
      - column-count
      - column-fill
      - column-gap
      - column-rule
      - column-rule-width
      - column-rule-style
      - column-rule-color
      - break-before
      - break-inside
      - break-after
      - page-break-before
      - page-break-inside
      - page-break-after
      - orphans
      - widows
      - zoom
      - max-zoom
      - min-zoom
      - user-zoom
      - orientation